import {ImageResponse} from 'next/og';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {getServerPreferences} from './preferences';
export async function productCover(help=false){
 const {locale}=await getServerPreferences();const thai=locale==='th';
 const title=help?(thai?'มีเรื่องสงสัย ค่อย ๆ คลายทีละข้อ':'A small question? Let’s untangle it.'):(thai?'ย่อลิงก์ให้สั้น ส่งต่อให้ง่าย':'Make room for the message.');
 const subtitle=help?(thai?'สร้าง · แชร์ · จัดการ · กู้คืน':'Create · Share · Manage · Recover'):(thai?'ลิงก์สั้น · QR Code · ไม่ต้องสมัครบัญชี':'Short links · QR codes · No sign-up');
 const [thaiFont,latinFont]=await Promise.all([readFile(join(process.cwd(),'public/fonts/ibm-plex-sans-thai-thai-500.woff')),readFile(join(process.cwd(),'public/fonts/ibm-plex-sans-thai-latin-500.woff'))]);
 return new ImageResponse(<div style={{display:'flex',position:'relative',width:'100%',height:'100%',background:'#f7f7f2',color:'#172b3a',padding:72,fontFamily:'MemoThai',overflow:'hidden'}}><div style={{display:'flex',flexDirection:'column',justifyContent:'space-between',width:650}}><div style={{display:'flex',alignItems:'center',gap:16,fontSize:30}}><div style={{display:'flex',width:48,height:48,borderRadius:12,background:'#244bd8',color:'white',justifyContent:'center',alignItems:'center'}}>M</div>MemoLink</div><div style={{display:'flex',flexDirection:'column'}}><div style={{display:'flex',fontSize:thai?64:74,lineHeight:1.3,maxWidth:650,letterSpacing:-2}}>{title}</div><div style={{display:'flex',fontSize:25,marginTop:28,color:'#566573'}}>{subtitle}</div></div><div style={{display:'flex',fontSize:18,color:'#566573'}}>l.memolab.me / {help?'help':'create'}</div></div><div style={{display:'flex',position:'absolute',right:55,top:115,width:330,height:260,borderRadius:22,border:'1px solid #cdd7df',background:'#fffefb',boxShadow:'9px 10px 0 #d7dcd9',transform:'rotate(-12deg)',padding:28,color:'#566573',fontSize:20}}>example.com/a-long-story</div><div style={{display:'flex',position:'absolute',right:90,top:240,width:315,height:285,borderRadius:22,background:'#244bd8',boxShadow:'9px 10px 0 #1736a4',transform:'rotate(8deg)',padding:30,flexDirection:'column',color:'white',justifyContent:'space-between'}}><div style={{display:'flex',fontSize:23}}>↗ MemoLink</div><div style={{display:'flex',fontSize:25}}>l.memolab.me/hello</div><div style={{display:'flex',width:'100%',borderTop:'1px solid #ffffff55',paddingTop:18,fontSize:18,color:'#dce995'}}>{thai?'พร้อมส่งต่อ':'Ready to share'} →</div></div><div style={{display:'flex',position:'absolute',right:52,top:165,width:115,height:68,borderRadius:12,background:'#dce995',boxShadow:'5px 6px 0 #acbb63',transform:'rotate(8deg)',justifyContent:'center',alignItems:'center',fontSize:22}}>hello.</div></div>,{width:1200,height:630,fonts:[{name:'MemoThai',data:thaiFont,weight:500},{name:'MemoThai',data:latinFont,weight:500}]});
}
