import type { Locale } from '@/config/i18n';

type ExperienceCopy={
  light:string;dark:string;system:string;close:string;
  shareTitle:string;shareBody:string;shareNative:string;copyLink:string;copied:string;copyCard:string;cardCopied:string;downloadCard:string;email:string;
  shareFeatureTitle:string;shareFeatureBody:string;
  faqSearch:string;faqAll:string;faqResults:string;faqNoResults:string;clearSearch:string;
};

export const experienceMessages:Record<Locale,ExperienceCopy>={
  en:{light:'Light',dark:'Dark',system:'System',close:'Close',shareTitle:'Share anywhere',shareBody:'Choose a channel. Your MemoLink preview is ready for every major sharing app.',shareNative:'More apps',copyLink:'Copy link',copied:'Link copied',copyCard:'Copy share card',cardCopied:'Share card copied',downloadCard:'Download card',email:'Email',shareFeatureTitle:'Share Kit',shareFeatureBody:'One clean preview for LINE, WhatsApp, Facebook, X, LinkedIn, Telegram and more.',faqSearch:'Search questions or answers',faqAll:'All topics',faqResults:'results',faqNoResults:'No matching answers yet. Try a shorter keyword or another topic.',clearSearch:'Clear search'},
  th:{light:'สว่าง',dark:'มืด',system:'ตามระบบ',close:'ปิด',shareTitle:'แชร์ได้ทุกที่',shareBody:'เลือกช่องทางที่ต้องการ MemoLink เตรียมตัวอย่างลิงก์ให้เหมาะกับแอปแชร์ยอดนิยมแล้ว',shareNative:'แอปอื่น ๆ',copyLink:'คัดลอกลิงก์',copied:'คัดลอกลิงก์แล้ว',copyCard:'คัดลอกภาพการ์ด',cardCopied:'คัดลอกภาพการ์ดแล้ว',downloadCard:'ดาวน์โหลดการ์ด',email:'อีเมล',shareFeatureTitle:'Share Kit',shareFeatureBody:'แชร์ไปยัง LINE, WhatsApp, Facebook, X, LinkedIn, Telegram และช่องทางอื่นได้จากจุดเดียว',faqSearch:'ค้นหาคำถามหรือคำตอบ',faqAll:'ทุกหัวข้อ',faqResults:'ผลลัพธ์',faqNoResults:'ยังไม่พบคำตอบที่ตรง ลองใช้คำค้นที่สั้นลงหรือเลือกหัวข้ออื่น',clearSearch:'ล้างคำค้น'},
  zh:{light:'浅色',dark:'深色',system:'跟随系统',close:'关闭',shareTitle:'分享到任何平台',shareBody:'选择渠道。MemoLink 已为主流分享应用准备好链接预览。',shareNative:'更多应用',copyLink:'复制链接',copied:'链接已复制',copyCard:'复制分享卡片',cardCopied:'分享卡片已复制',downloadCard:'下载卡片',email:'电子邮件',shareFeatureTitle:'分享工具包',shareFeatureBody:'从一个入口分享到 LINE、WhatsApp、Facebook、X、LinkedIn、Telegram 等平台。',faqSearch:'搜索问题或答案',faqAll:'全部主题',faqResults:'条结果',faqNoResults:'暂未找到匹配答案，请缩短关键词或选择其他主题。',clearSearch:'清除搜索'},
  ja:{light:'ライト',dark:'ダーク',system:'システム',close:'閉じる',shareTitle:'どこへでも共有',shareBody:'共有先を選択してください。主要アプリ向けのMemoLinkプレビューが用意されています。',shareNative:'その他のアプリ',copyLink:'リンクをコピー',copied:'リンクをコピーしました',copyCard:'共有カードをコピー',cardCopied:'共有カードをコピーしました',downloadCard:'カードを保存',email:'メール',shareFeatureTitle:'Share Kit',shareFeatureBody:'LINE、WhatsApp、Facebook、X、LinkedIn、Telegramなどへ一か所から共有できます。',faqSearch:'質問や回答を検索',faqAll:'すべてのトピック',faqResults:'件',faqNoResults:'一致する回答がありません。短いキーワードや別のトピックをお試しください。',clearSearch:'検索をクリア'},
  ko:{light:'라이트',dark:'다크',system:'시스템',close:'닫기',shareTitle:'어디서나 공유',shareBody:'채널을 선택하세요. 주요 공유 앱에 맞는 MemoLink 미리보기가 준비되어 있습니다.',shareNative:'다른 앱',copyLink:'링크 복사',copied:'링크를 복사했습니다',copyCard:'공유 카드 복사',cardCopied:'공유 카드를 복사했습니다',downloadCard:'카드 다운로드',email:'이메일',shareFeatureTitle:'Share Kit',shareFeatureBody:'LINE, WhatsApp, Facebook, X, LinkedIn, Telegram 등에 한곳에서 공유하세요.',faqSearch:'질문 또는 답변 검색',faqAll:'모든 주제',faqResults:'개 결과',faqNoResults:'일치하는 답변이 없습니다. 더 짧은 검색어나 다른 주제를 사용해 보세요.',clearSearch:'검색 지우기'},
  es:{light:'Claro',dark:'Oscuro',system:'Sistema',close:'Cerrar',shareTitle:'Comparte en cualquier lugar',shareBody:'Elige un canal. MemoLink prepara una vista previa compatible con las principales aplicaciones.',shareNative:'Más aplicaciones',copyLink:'Copiar enlace',copied:'Enlace copiado',copyCard:'Copiar tarjeta',cardCopied:'Tarjeta copiada',downloadCard:'Descargar tarjeta',email:'Correo',shareFeatureTitle:'Kit para compartir',shareFeatureBody:'Comparte en LINE, WhatsApp, Facebook, X, LinkedIn, Telegram y más desde un solo lugar.',faqSearch:'Buscar preguntas o respuestas',faqAll:'Todos los temas',faqResults:'resultados',faqNoResults:'No encontramos una respuesta. Prueba una palabra más corta u otro tema.',clearSearch:'Borrar búsqueda'}
};
