export const landingCopy = {
  en: {
    eyebrow: 'A little link. A lot of possibility.', title: 'Big ideas.', accent: 'Short links.',
    intro: 'Your next launch, a favourite find, that thing worth sharing. Give it a link that’s easy to pass along.',
    definition: 'MemoLink is a free URL shortener with QR codes, custom link names, passwords and expiry settings. Start without an account.',
    create: 'Make your first link', explore: 'See what fits your day', formTitle: 'Something worth sharing?', formHint: 'Paste your URL. We’ll take the long way out.',
    example: 'An example, made for your everyday', long: 'The link you have', short: 'The link you share',
    useLabel: 'Try a different story', examples: ['A creative portfolio', 'Your next event', 'A favourite recipe'],
    ribbon: ['Less clutter.', 'More character.', 'Ready to share.'],
    sectionLabel: 'SMALL DETAILS. BETTER SHARING.', sectionTitle: 'Make the link\nfeel like you.', sectionBody: 'A thoughtful name. The right access. A way to take it offline. Start simple, then add what your link needs.',
    cards: [
      ['A name worth remembering.', 'Turn a string of characters into a name that tells people where they’re going. Choose an available name when you create your link.'],
      ['Share on your terms.', 'Add a password for your recipients. Set an end date or a click limit when the moment has a deadline.'],
      ['From screen to somewhere.', 'Download a QR code for your poster, menu or business card. One link, with another way in.'],
    ],
    howLabel: 'FROM A LONG URL TO “HERE YOU GO”', howTitle: 'Three small steps.\nYou’re on your way.',
    steps: [['Bring your link', 'Paste the full web address you want to share.'], ['Make it yours', 'Keep it simple, or add a name, password and expiry.'], ['Send it out', 'Copy your short link or download its QR code.']],
    ownershipLabel: 'NO SIGN-UP. ONE THING TO REMEMBER.', ownershipTitle: 'Your links live here.\nKeep the key with you.', ownershipBody: 'Manage your links in this browser without an account. Before switching browsers or clearing site data, save your recovery key from My links. It lets you restore access elsewhere.', ownershipCta: 'Open My links',
    faqLabel: 'BEFORE YOU SHARE', faqTitle: 'A few good questions.', faqMore: 'More answers in the help centre',
    faqs: [
      ['What is MemoLink?', 'MemoLink is a free tool that turns long web addresses into short links. You can choose a custom name, generate a QR code, add a password and set when a link expires.'],
      ['Do I need to create an account?', 'No. MemoLink saves a private management key in your browser. Open My links in the same browser to manage the links you create.'],
      ['Can I use a short link on a printed poster?', 'Yes. Create your link, then download its QR code. Test the code before printing, and check any expiry or click limit you have set.'],
      ['What happens if I change devices?', 'Save your recovery key from My links before you switch. Import it on the new device to restore management access. Keep the key private: anyone who has it can manage your links.'],
    ],
    finalTitle: 'Good things\ndeserve to travel.', finalBody: 'Start with a link. See where it goes.', finalCta: 'Let’s make it shorter',
    clipboardError: 'Clipboard access is unavailable. Please copy or paste the link manually.',
  },
  th: {
    eyebrow: 'ลิงก์เล็ก ๆ ที่พาไอเดียไปต่อ', title: 'ไอเดียไม่ต้องย่อ', accent: 'แค่ลิงก์ก็พอ',
    intro: 'ผลงานที่ภูมิใจ งานที่อยากชวนไป หรือเรื่องดี ๆ ที่อยากส่งต่อ ให้ทุกการแชร์เริ่มด้วยลิงก์สั้น ๆ ที่จำง่าย',
    definition: 'MemoLink คือเครื่องมือย่อลิงก์ฟรี พร้อมสร้าง QR Code ตั้งชื่อลิงก์ รหัสผ่าน และวันหมดอายุ เริ่มใช้ได้โดยไม่ต้องสมัครบัญชี',
    create: 'เริ่มย่อลิงก์ของคุณ', explore: 'ดูไอเดียการใช้งาน', formTitle: 'มีอะไรดี ๆ อยากส่งต่อไหม?', formHint: 'วางลิงก์ที่นี่ เดี๋ยวช่วยทำให้สั้นลง',
    example: 'ตัวอย่างลิงก์สำหรับเรื่องใกล้ตัว', long: 'จากลิงก์ที่มี', short: 'เป็นลิงก์ที่พร้อมแชร์',
    useLabel: 'ลองเลือกเรื่องที่อยากแชร์', examples: ['พอร์ตผลงาน', 'งานที่อยากชวนไป', 'สูตรอร่อยที่อยากบอกต่อ'],
    ribbon: ['สั้นลงนิด', 'จำง่ายขึ้น', 'ส่งต่อได้เลย'],
    sectionLabel: 'ใส่ใจอีกนิด แชร์ได้ดีกว่าเดิม', sectionTitle: 'ลิงก์ของคุณ\nในแบบที่เป็นคุณ', sectionBody: 'ชื่อที่สื่อความหมาย คนที่เข้าถึงได้ หรือ QR ที่พาไปต่อจากหน้ากระดาษ เลือกเพิ่มเฉพาะสิ่งที่ลิงก์ของคุณต้องการ',
    cards: [
      ['ชื่อสั้น ๆ ที่บอกอะไรได้มาก', 'เปลี่ยนชุดตัวอักษรให้เป็นชื่อที่คนอ่านแล้วรู้ว่าจะเจออะไร เลือกชื่อที่ยังว่างได้ตอนสร้างลิงก์'],
      ['แชร์ได้ ในขอบเขตที่เลือก', 'เพิ่มรหัสผ่านให้คนรับ หรือกำหนดวันหมดอายุและจำนวนคลิก เมื่อลิงก์นั้นมีช่วงเวลาของมัน'],
      ['จากหน้าจอ ไปถึงหน้าร้าน', 'ดาวน์โหลด QR Code ไปวางบนโปสเตอร์ เมนู หรือนามบัตร ลิงก์เดิม เพิ่มอีกทางให้คนเข้าถึง'],
    ],
    howLabel: 'จากลิงก์ยาว ๆ ถึงคำว่า “ส่งให้แล้วนะ”', howTitle: 'ไม่กี่ขั้นตอน\nก็พร้อมส่งต่อ',
    steps: [['วางลิงก์ที่มี', 'คัดลอกที่อยู่เว็บฉบับเต็มที่อยากแชร์มาวาง'], ['เติมสิ่งที่ต้องการ', 'ใช้ได้เลย หรือเพิ่มชื่อ รหัสผ่าน และวันหมดอายุ'], ['แชร์ได้ทันที', 'คัดลอกลิงก์สั้น หรือดาวน์โหลด QR Code ไปใช้']],
    ownershipLabel: 'ไม่ต้องสมัคร แต่มีสิ่งหนึ่งที่อยากให้เก็บไว้', ownershipTitle: 'ลิงก์อยู่ที่นี่\nอย่าลืมเก็บกุญแจไว้ด้วย', ownershipBody: 'กลับมาจัดการลิงก์ในเบราว์เซอร์นี้ได้โดยไม่ต้องมีบัญชี ก่อนเปลี่ยนเบราว์เซอร์หรือล้างข้อมูลเว็บไซต์ อย่าลืมสำรอง Recovery key จาก “ลิงก์ของฉัน” เพื่อกู้คืนสิทธิ์จัดการบนอุปกรณ์อื่น', ownershipCta: 'ไปที่ลิงก์ของฉัน',
    faqLabel: 'ก่อนส่งลิงก์ต่อ', faqTitle: 'เรื่องที่อาจอยากรู้', faqMore: 'อ่านคำตอบเพิ่มเติม',
    faqs: [
      ['MemoLink คืออะไร?', 'MemoLink คือเครื่องมือย่อลิงก์ฟรีที่เปลี่ยนที่อยู่เว็บยาว ๆ ให้เป็นลิงก์สั้น คุณสามารถตั้งชื่อลิงก์ สร้าง QR Code เพิ่มรหัสผ่าน และกำหนดวันหมดอายุได้'],
      ['ต้องสมัครบัญชีก่อนไหม?', 'ไม่ต้องสมัคร MemoLink เก็บคีย์สำหรับจัดการลิงก์ไว้ในเบราว์เซอร์ เปิด “ลิงก์ของฉัน” จากเบราว์เซอร์เดิมเพื่อจัดการลิงก์ที่สร้างไว้ได้เลย'],
      ['นำลิงก์ไปใช้บนโปสเตอร์ได้ไหม?', 'ได้ เมื่อสร้างลิงก์แล้ว ให้ดาวน์โหลด QR Code ไปใช้ ควรทดสอบสแกนก่อนพิมพ์ และตรวจสอบวันหมดอายุหรือจำนวนคลิกที่จำกัดไว้ด้วย'],
      ['เปลี่ยนอุปกรณ์แล้วลิงก์จะหายไหม?', 'ให้สำรอง Recovery key จาก “ลิงก์ของฉัน” ก่อนเปลี่ยนอุปกรณ์ แล้วนำคีย์ไปกู้คืนสิทธิ์จัดการบนเครื่องใหม่ เก็บคีย์นี้เป็นความลับ เพราะผู้ที่มีคีย์สามารถจัดการลิงก์ของคุณได้'],
    ],
    finalTitle: 'เรื่องดี ๆ\nมีไว้ให้ส่งต่อ', finalBody: 'เริ่มจากลิงก์ของคุณ แล้วให้มันเดินทางต่อ', finalCta: 'มาย่อลิงก์กัน',
    clipboardError: 'เข้าถึงคลิปบอร์ดไม่ได้ ลองคัดลอกหรือวางลิงก์ด้วยตัวเองอีกครั้งนะ',
  },
} as const;
