import { Locale } from './i18n';

export const pageMessages = {
  en: {
    navHome:'Home', navCreate:'Create', navLinks:'My links', navFaq:'Help',
    dashboardEyebrow:'PRIVATE ANALYTICS', dashboardTitle:'My links', dashboardDescription:'Manage links and understand how they are used.', createLink:'+ Create link', recovery:'Recovery key',
    noLinks:'No links yet', noLinksBody:'Create your first short link in seconds.', loadingLinks:'Loading links…', clicks:'clicks', created:'Created', lastVisit:'Last visit', live:'Live', paused:'Paused',
    copy:'Copy', pause:'Pause', activate:'Activate', delete:'Delete', analytics:'Analytics', visits30d:'Last 30 days', countries:'Countries', devices:'Devices', referrers:'Referrers', noAnalytics:'Analytics will appear after the first visit.',
    recoverTitle:'Move link ownership', recoverBody:'Keep this key private. Anyone with it can manage your links.', copyRecovery:'Copy recovery key', pasteRecovery:'Paste recovery key', restore:'Restore',
    checking:'Opening link…', protectedTitle:'Password required', protectedBody:'Enter the password shared by the link owner.', password:'Password', continue:'Continue', unavailable:'Link unavailable', unavailableBody:'It may be paused, expired or have reached its limit.', missing:'Link not found', missingBody:'Check the address or ask the owner for a new link.', retryTitle:'Could not open the link', retryBody:'Check your connection and try again.', retry:'Try again',
    faqTitle:'Help center', faqDescription:'Practical answers for creating, sharing and managing links.',
    faqSections:[
      ['Creating links',[
        ['Which URLs can I shorten?','MemoLink supports public HTTP and HTTPS addresses. Localhost and private network destinations are blocked for safety.'],
        ['Can I choose the short name?','Yes. Open Link settings and enter 3–48 letters, numbers, hyphens or underscores. Reserved and existing names cannot be used.'],
        ['What does clean tracking do?','It removes common advertising parameters such as utm_*, gclid and fbclid before applying the UTM values you enter.']
      ]],
      ['Access and expiration',[
        ['How does password protection work?','The password is hashed before storage and is submitted through a secure request body, never inside the URL.'],
        ['When does a click-limited link expire?','Each successful redirect consumes one click atomically. When the limit is reached, the link stops redirecting.'],
        ['Which timezone is used?','The expiration form uses your device timezone and stores the resulting instant consistently on the server.']
      ]],
      ['Ownership and analytics',[
        ['Why are my links tied to this device?','A private recovery key is generated in this browser. The server stores only its one-way hash, so no account is required.'],
        ['How do I move to another device?','Copy the recovery key from My links, store it securely and restore it on the new device.'],
        ['What analytics are collected?','MemoLink stores aggregate day, country, device category and referrer domain counts. It does not store raw IP addresses.']
      ]]
    ]
  },
  th: {
    navHome:'หน้าแรก',navCreate:'สร้างลิงก์',navLinks:'ลิงก์ของฉัน',navFaq:'ช่วยเหลือ',dashboardEyebrow:'สถิติส่วนตัว',dashboardTitle:'ลิงก์ของฉัน',dashboardDescription:'จัดการลิงก์และดูภาพรวมการใช้งาน',createLink:'+ สร้างลิงก์',recovery:'Recovery key',noLinks:'ยังไม่มีลิงก์',noLinksBody:'สร้างลิงก์แรกได้ในไม่กี่วินาที',loadingLinks:'กำลังโหลด…',clicks:'คลิก',created:'สร้างเมื่อ',lastVisit:'เข้าล่าสุด',live:'ใช้งาน',paused:'หยุด',copy:'คัดลอก',pause:'หยุด',activate:'เปิดใช้',delete:'ลบ',analytics:'สถิติ',visits30d:'30 วันล่าสุด',countries:'ประเทศ',devices:'อุปกรณ์',referrers:'แหล่งที่มา',noAnalytics:'สถิติจะแสดงหลังมีผู้เข้าชม',recoverTitle:'ย้ายสิทธิ์จัดการลิงก์',recoverBody:'เก็บคีย์นี้เป็นความลับ ผู้ที่มีคีย์สามารถจัดการลิงก์ได้',copyRecovery:'คัดลอก Recovery key',pasteRecovery:'วาง Recovery key',restore:'กู้คืน',checking:'กำลังเปิดลิงก์…',protectedTitle:'ต้องใช้รหัสผ่าน',protectedBody:'กรอกรหัสผ่านที่ได้รับจากเจ้าของลิงก์',password:'รหัสผ่าน',continue:'ดำเนินการต่อ',unavailable:'ลิงก์ไม่พร้อมใช้งาน',unavailableBody:'ลิงก์อาจถูกหยุด หมดอายุ หรือครบจำนวนคลิก',missing:'ไม่พบลิงก์',missingBody:'ตรวจสอบที่อยู่หรือขอลิงก์ใหม่จากเจ้าของ',retryTitle:'เปิดลิงก์ไม่สำเร็จ',retryBody:'ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง',retry:'ลองอีกครั้ง',faqTitle:'ศูนย์ช่วยเหลือ',faqDescription:'คำตอบที่ใช้ได้จริงสำหรับการสร้าง แชร์ และจัดการลิงก์',
    faqSections:[['การสร้างลิงก์',[['ย่อลิงก์แบบใดได้บ้าง?','รองรับที่อยู่ HTTP และ HTTPS สาธารณะ โดยบล็อก localhost และเครือข่ายส่วนตัวเพื่อความปลอดภัย'],['ตั้งชื่อสั้นเองได้ไหม?','ได้ เปิดตั้งค่าลิงก์แล้วใช้ตัวอักษร ตัวเลข ขีดกลาง หรือขีดล่าง 3–48 ตัว'],['Clean tracking ทำอะไร?','ลบพารามิเตอร์โฆษณาเดิม เช่น utm_*, gclid และ fbclid ก่อนใส่ค่า UTM ใหม่']]],['การเข้าถึงและหมดอายุ',[['รหัสผ่านปลอดภัยอย่างไร?','ระบบ hash รหัสผ่านก่อนบันทึกและไม่ส่งรหัสผ่านไว้ใน URL'],['จำกัดคลิกทำงานอย่างไร?','ทุก redirect ที่สำเร็จจะเพิ่มจำนวนแบบ atomic และหยุดทันทีเมื่อครบกำหนด'],['ใช้เขตเวลาใด?','แบบฟอร์มใช้เขตเวลาของอุปกรณ์และจัดเก็บเวลาอ้างอิงเดียวกันบนเซิร์ฟเวอร์']]],['สิทธิ์และสถิติ',[['ทำไมลิงก์ผูกกับอุปกรณ์?','เบราว์เซอร์สร้าง Recovery key ส่วนตัว ส่วนเซิร์ฟเวอร์เก็บเพียงค่า hash จึงไม่ต้องสมัครบัญชี'],['ย้ายอุปกรณ์อย่างไร?','คัดลอก Recovery key จากลิงก์ของฉัน เก็บให้ปลอดภัย แล้วกู้คืนบนอุปกรณ์ใหม่'],['เก็บข้อมูลสถิติอะไร?','เก็บเฉพาะยอดรวมรายวัน ประเทศ ประเภทอุปกรณ์ และโดเมนต้นทาง โดยไม่เก็บ IP ดิบ']]]]
  },
  zh: {
    navHome:'首页',navCreate:'创建',navLinks:'我的链接',navFaq:'帮助',dashboardEyebrow:'私人分析',dashboardTitle:'我的链接',dashboardDescription:'管理链接并了解使用情况',createLink:'+ 创建链接',recovery:'恢复密钥',noLinks:'暂无链接',noLinksBody:'几秒钟即可创建第一个短链接',loadingLinks:'加载中…',clicks:'次点击',created:'创建于',lastVisit:'最近访问',live:'启用',paused:'暂停',copy:'复制',pause:'暂停',activate:'启用',delete:'删除',analytics:'分析',visits30d:'最近30天',countries:'国家',devices:'设备',referrers:'来源',noAnalytics:'首次访问后将显示分析数据',recoverTitle:'迁移链接所有权',recoverBody:'请妥善保管此密钥，持有者可管理你的链接',copyRecovery:'复制恢复密钥',pasteRecovery:'粘贴恢复密钥',restore:'恢复',checking:'正在打开…',protectedTitle:'需要密码',protectedBody:'输入链接所有者提供的密码',password:'密码',continue:'继续',unavailable:'链接不可用',unavailableBody:'链接可能已暂停、过期或达到访问限制',missing:'找不到链接',missingBody:'请检查地址或向所有者索取新链接',retryTitle:'无法打开链接',retryBody:'请检查网络后重试',retry:'重试',faqTitle:'帮助中心',faqDescription:'创建、分享和管理链接的实用解答',
    faqSections:[['创建链接',[['支持哪些链接？','支持公开的 HTTP 和 HTTPS 地址，并出于安全原因阻止本地及私有网络地址。'],['可以自定义短名称吗？','可以，使用3–48个字母、数字、连字符或下划线。'],['清理跟踪参数有什么作用？','先移除 utm_*、gclid 和 fbclid 等参数，再应用新的 UTM 值。']]],['访问与过期',[['密码如何保护？','密码在存储前会被哈希，并通过请求正文提交，不会出现在 URL 中。'],['点击限制如何计算？','每次成功跳转都会原子计数，达到限制后立即停止。'],['使用哪个时区？','表单使用设备时区，服务器统一保存对应时间。']]],['所有权与分析',[['为何绑定设备？','浏览器生成私人恢复密钥，服务器只保存单向哈希，因此无需账户。'],['如何迁移设备？','在我的链接中复制恢复密钥，并在新设备上恢复。'],['收集哪些分析数据？','仅保存按日、国家、设备类型和来源域名汇总的数据，不保存原始 IP。']]]]
  },
  ja: {
    navHome:'ホーム',navCreate:'作成',navLinks:'マイリンク',navFaq:'ヘルプ',dashboardEyebrow:'プライベート分析',dashboardTitle:'マイリンク',dashboardDescription:'リンクを管理し利用状況を確認',createLink:'+ リンク作成',recovery:'復旧キー',noLinks:'リンクはまだありません',noLinksBody:'数秒で最初のリンクを作成できます',loadingLinks:'読み込み中…',clicks:'クリック',created:'作成日',lastVisit:'最終訪問',live:'有効',paused:'停止中',copy:'コピー',pause:'停止',activate:'有効化',delete:'削除',analytics:'分析',visits30d:'過去30日',countries:'国',devices:'デバイス',referrers:'参照元',noAnalytics:'最初の訪問後に分析が表示されます',recoverTitle:'所有権を移行',recoverBody:'このキーは秘密に保管してください',copyRecovery:'復旧キーをコピー',pasteRecovery:'復旧キーを貼り付け',restore:'復元',checking:'リンクを開いています…',protectedTitle:'パスワードが必要です',protectedBody:'所有者から共有されたパスワードを入力',password:'パスワード',continue:'続ける',unavailable:'リンクは利用できません',unavailableBody:'停止、期限切れ、または上限に達した可能性があります',missing:'リンクが見つかりません',missingBody:'URLを確認するか新しいリンクを依頼してください',retryTitle:'リンクを開けませんでした',retryBody:'接続を確認して再試行してください',retry:'再試行',faqTitle:'ヘルプセンター',faqDescription:'リンクの作成・共有・管理に役立つ回答',
    faqSections:[['リンク作成',[['どのURLを短縮できますか？','公開HTTP/HTTPSに対応し、安全のためローカルおよびプライベートネットワークは拒否します。'],['短い名前を選べますか？','3〜48文字の英数字、ハイフン、アンダースコアを使用できます。'],['トラッキング削除とは？','utm_*、gclid、fbclidを削除してから新しいUTM値を設定します。']]],['アクセスと期限',[['パスワードは安全ですか？','保存前にハッシュ化し、URLではなく安全なリクエスト本文で送信します。'],['クリック制限は？','成功した転送を原子的に数え、上限に達すると停止します。'],['タイムゾーンは？','端末の時間帯を使用し、サーバーでは一貫した時刻として保存します。']]],['所有権と分析',[['なぜ端末に紐づく？','ブラウザが秘密の復旧キーを生成し、サーバーは一方向ハッシュだけを保存します。'],['端末を移行するには？','マイリンクから復旧キーをコピーし、新しい端末で復元します。'],['収集する分析情報は？','日別・国・端末カテゴリ・参照ドメインの集計のみで、生IPは保存しません。']]]]
  },
  ko: {
    navHome:'홈',navCreate:'만들기',navLinks:'내 링크',navFaq:'도움말',dashboardEyebrow:'비공개 분석',dashboardTitle:'내 링크',dashboardDescription:'링크를 관리하고 사용 현황을 확인하세요',createLink:'+ 링크 만들기',recovery:'복구 키',noLinks:'링크가 없습니다',noLinksBody:'몇 초 안에 첫 링크를 만드세요',loadingLinks:'불러오는 중…',clicks:'클릭',created:'생성',lastVisit:'최근 방문',live:'사용 중',paused:'일시 중지',copy:'복사',pause:'중지',activate:'활성화',delete:'삭제',analytics:'분석',visits30d:'최근 30일',countries:'국가',devices:'기기',referrers:'유입 경로',noAnalytics:'첫 방문 후 분석이 표시됩니다',recoverTitle:'링크 소유권 이동',recoverBody:'이 키는 비공개로 보관하세요',copyRecovery:'복구 키 복사',pasteRecovery:'복구 키 붙여넣기',restore:'복원',checking:'링크 여는 중…',protectedTitle:'비밀번호 필요',protectedBody:'링크 소유자가 공유한 비밀번호를 입력하세요',password:'비밀번호',continue:'계속',unavailable:'링크를 사용할 수 없음',unavailableBody:'중지, 만료 또는 제한 도달 상태일 수 있습니다',missing:'링크를 찾을 수 없음',missingBody:'주소를 확인하거나 새 링크를 요청하세요',retryTitle:'링크를 열 수 없음',retryBody:'연결을 확인하고 다시 시도하세요',retry:'다시 시도',faqTitle:'도움말 센터',faqDescription:'링크 생성, 공유 및 관리에 필요한 실용적인 답변',
    faqSections:[['링크 만들기',[['어떤 URL을 줄일 수 있나요?','공개 HTTP/HTTPS를 지원하며 안전을 위해 로컬 및 사설 네트워크 주소를 차단합니다.'],['짧은 이름을 선택할 수 있나요?','3~48자의 영문, 숫자, 하이픈 또는 밑줄을 사용할 수 있습니다.'],['추적 정리는 무엇인가요?','utm_*, gclid, fbclid를 제거한 뒤 새 UTM 값을 적용합니다.']]],['접근 및 만료',[['비밀번호는 안전한가요?','저장 전에 해시하며 URL이 아닌 안전한 요청 본문으로 전송합니다.'],['클릭 제한은 어떻게 계산하나요?','성공한 리디렉션을 원자적으로 계산하고 한도에 도달하면 중단합니다.'],['어떤 시간대를 사용하나요?','기기 시간대를 사용하고 서버에는 일관된 시점으로 저장합니다.']]],['소유권 및 분석',[['왜 기기에 연결되나요?','브라우저가 비공개 복구 키를 만들고 서버는 단방향 해시만 저장합니다.'],['기기를 이동하려면?','내 링크에서 복구 키를 복사해 새 기기에서 복원하세요.'],['어떤 분석을 수집하나요?','일자, 국가, 기기 유형, 유입 도메인의 집계만 저장하며 원시 IP는 저장하지 않습니다.']]]]
  }
} satisfies Record<Locale, { faqSections: Array<[string, Array<[string,string]>]> } & Record<string, unknown>>;

export function getPageMessages(locale: Locale) {
  return pageMessages[locale] as typeof pageMessages.en;
}
