import type { Locale } from './i18n';

const en = {
  eyebrow: 'Less URL. More you.', heroFirst: 'Long story.', heroSecond: 'Short link.',
  heroBody: 'Your work, your next event, that thing worth sharing. Give it a shorter address and send it on its way.',
  composerTitle: 'Where are we going?', composerHint: 'Paste a web address. We’ll take care of the length.', free: 'Free to use', noSignup: 'No sign-up', qrIncluded: 'QR code included',
  example: 'An example, made for you', portfolio: 'Your work', event: 'An invitation', campaign: 'A campaign',
  exampleNames: ['my-work', 'see-you-there', 'new-collection'], exampleDestinations: ['example.com/portfolio/selected-work', 'example.com/events/a-night-to-remember', 'example.com/shop/new-collection?utm_source=instagram'],
  exampleNote: 'Illustration only. Your link is created in the form above.',
  featuresKicker: 'Small link, thoughtful details', featuresTitle: 'Share it your way.',
  qrTitle: 'From screen to anywhere.', qrBody: 'A QR code for the counter, a poster or a business card. Change the destination later and keep the same code.',
  accessTitle: 'A little more control.', accessBody: 'Add a password. Choose an expiry date. Or set a limit on visits. Only turn on what you need.',
  manageFeatureTitle: 'The story continues after sharing.', manageFeatureBody: 'See aggregate visits, update the destination or pause a link. Everything you’ve made lives in My links.',
  stepsTitle: 'From paste to passed along.', steps: [['Paste it', 'Start with the destination you want to share.'], ['Make it yours', 'Choose a name or let us make one. Add settings if you need them.'], ['Send it', 'Copy the link, save the QR code or open the share menu.']],
  recoveryTitle: 'Your links travel with a key.', recoveryBody: 'No account to remember. Save your recovery key from My links before changing devices or clearing browser storage.', recoveryAction: 'Find my recovery key',
  faqEyebrow: 'A good place to get unstuck', faqTitle: 'A few questions. Clear answers.', faqBody: 'Creating your first link or finding your way back? Start here.',
  manageEyebrow: 'Your little corner of the internet', manageTitle: 'Made by you. Managed here.', manageBody: 'Keep your links in order, see where they go and decide what happens next.',
  deviceNote: 'Showing links owned by this browser. Use a recovery key to move them here.', listLimit: 'Showing your 200 most recent links. Search and filters apply to this list.',
  collection: 'Your collection', reset: 'Clear filters', results: 'matching links', cancel: 'Cancel', emptyAnalytics: 'No visits in this period yet.',
  footerLine: 'Good things deserve a good link.', footerBody: 'Short links, QR codes and a little more room to share.', footerAction: 'Make a link',
};
type Copy = { [K in keyof typeof en]: (typeof en)[K] extends string ? string : (typeof en)[K] };

export const studioMessages: Record<Locale, Copy> = {
  en,
  th: {
    eyebrow:'เรื่องที่อยากแชร์ เริ่มที่ลิงก์เดียว', heroFirst:'เรื่องราวไปได้ไกล', heroSecond:'ในลิงก์ที่สั้นลง',
    heroBody:'ผลงานที่ตั้งใจทำ งานที่อยากชวนมา หรือเรื่องดี ๆ ที่อยากส่งต่อ ย่อลิงก์ให้จำง่าย แล้วแชร์ในแบบของคุณ',
    composerTitle:'อยากพาไปที่ไหน?', composerHint:'วางที่อยู่เว็บไซต์ แล้วให้เราย่อให้สั้นลง', free:'ใช้งานฟรี', noSignup:'ไม่ต้องสมัคร', qrIncluded:'พร้อม QR Code',
    example:'ลองดูว่าลิงก์ของคุณจะเป็นแบบไหน', portfolio:'แชร์ผลงาน', event:'ชวนมางาน', campaign:'เปิดตัวแคมเปญ',
    exampleNames:['my-work','see-you-there','new-collection'], exampleDestinations:en.exampleDestinations,
    exampleNote:'ตัวอย่างประกอบเท่านั้น สร้างลิงก์จริงได้จากฟอร์มด้านบน',
    featuresKicker:'รายละเอียดเล็ก ๆ ที่คิดเผื่อไว้', featuresTitle:'แชร์แบบที่ใช่สำหรับคุณ',
    qrTitle:'จากหน้าจอ ไปได้ทุกที่', qrBody:'วาง QR Code บนเคาน์เตอร์ โปสเตอร์ หรือนามบัตร เปลี่ยนปลายทางภายหลังได้ โดยใช้โค้ดเดิม',
    accessTitle:'เลือกได้ว่าใครเปิด และเปิดถึงเมื่อไร', accessBody:'ใส่รหัสผ่าน ตั้งวันหมดอายุ หรือจำกัดจำนวนครั้งที่เปิด เลือกใช้เฉพาะสิ่งที่คุณต้องการ',
    manageFeatureTitle:'แชร์แล้ว ก็ยังดูแลต่อได้', manageFeatureBody:'ดูยอดเข้าชม เปลี่ยนปลายทาง หรือพักการใช้งาน ลิงก์ที่สร้างไว้กลับมาจัดการได้ใน “ลิงก์ของฉัน”',
    stepsTitle:'จากลิงก์ยาว สู่เรื่องที่ส่งต่อ', steps:[['วางลิงก์','เริ่มจากเว็บไซต์ที่อยากพาคนไปดู'],['ปรับให้เป็นคุณ','ตั้งชื่อเองหรือให้เราสร้างให้ เพิ่มตัวเลือกได้ตามต้องการ'],['พร้อมส่งต่อ','คัดลอกลิงก์ บันทึก QR Code หรือเปิดเมนูแชร์']],
    recoveryTitle:'ย้ายเครื่อง ลิงก์ก็ไปด้วยได้', recoveryBody:'ไม่ต้องจำบัญชี แต่ต้องเก็บคีย์กู้คืนไว้ เปิด “ลิงก์ของฉัน” เพื่อสำรองคีย์ก่อนเปลี่ยนอุปกรณ์หรือล้างข้อมูลเบราว์เซอร์', recoveryAction:'ดูคีย์กู้คืนของฉัน',
    faqEyebrow:'ติดตรงไหน เริ่มที่นี่', faqTitle:'คำถามที่เจอ คำตอบที่ใช้ได้', faqBody:'ตั้งแต่สร้างลิงก์แรก ไปจนถึงกู้คืนลิงก์เดิม หาคำตอบได้ที่นี่',
    manageEyebrow:'พื้นที่เล็ก ๆ ของเรื่องที่คุณแชร์', manageTitle:'สร้างไว้ที่ไหน ดูแลต่อที่นี่', manageBody:'รวมลิงก์ของคุณไว้ให้หาเจอ ดูยอดเข้าชม และจัดการปลายทางได้ในที่เดียว',
    deviceNote:'แสดงลิงก์ที่เบราว์เซอร์นี้มีสิทธิ์จัดการ ย้ายลิงก์มาที่นี่ได้ด้วยคีย์กู้คืน', listLimit:'แสดง 200 ลิงก์ล่าสุด การค้นหาและตัวกรองใช้กับรายการนี้',
    collection:'ลิงก์ที่คุณสร้าง', reset:'ล้างตัวกรอง', results:'ลิงก์ที่ตรงกัน', cancel:'ยกเลิก', emptyAnalytics:'ยังไม่มีการเข้าชมในช่วงเวลานี้',
    footerLine:'เรื่องดี ๆ มีลิงก์ไว้ส่งต่อ', footerBody:'ลิงก์สั้น QR Code และพื้นที่ให้เรื่องราวไปต่อ', footerAction:'สร้างลิงก์สั้น',
  },
  zh: {...en,eyebrow:'短一点，更像你',heroFirst:'故事很长。',heroSecond:'链接很短。',heroBody:'作品、活动或值得分享的事，给它一个更短的地址。',composerTitle:'想带大家去哪里？',composerHint:'粘贴网页地址，我们来缩短。',free:'免费使用',noSignup:'无需注册',qrIncluded:'附带二维码',example:'看看链接的样子',portfolio:'作品',event:'邀请',campaign:'推广',exampleNote:'仅为示例，请在上方表单创建链接。',featuresKicker:'为你考虑的小细节',featuresTitle:'按你的方式分享。',qrTitle:'从屏幕到更多地方。',qrBody:'为海报、柜台或名片保存二维码。更换目标地址后，二维码仍可使用。',accessTitle:'多一点掌控。',accessBody:'按需添加密码、有效期或访问次数限制。',manageFeatureTitle:'分享后，还能继续管理。',manageFeatureBody:'查看汇总访问量、更换目标或暂停链接。',stepsTitle:'从粘贴到分享。',steps:[['粘贴','输入要分享的网页。'],['定制','选择名称并按需添加设置。'],['分享','复制链接、保存二维码或打开分享菜单。']],recoveryTitle:'用密钥带走你的链接。',recoveryBody:'换设备或清除浏览器数据前，在“我的链接”保存恢复密钥。',recoveryAction:'查看恢复密钥',faqEyebrow:'遇到问题，从这里开始',faqTitle:'问题与清晰的答案。',faqBody:'创建、管理与恢复链接的实用解答。',manageEyebrow:'你分享的那些事',manageTitle:'你的链接，在这里管理。',manageBody:'查看访问量，整理链接，管理目标地址。',deviceNote:'显示此浏览器拥有的链接，可用恢复密钥迁移。',listLimit:'显示最近200个链接，搜索和筛选适用于此列表。',collection:'我的链接集合',reset:'清除筛选',results:'个匹配链接',cancel:'取消',emptyAnalytics:'此期间暂无访问。',footerLine:'好事值得分享。',footerBody:'短链接、二维码，让分享更简单。',footerAction:'创建链接'},
  ja: {...en,eyebrow:'短いURLで、あなたらしく',heroFirst:'伝えたいことは、',heroSecond:'短いリンクで。',heroBody:'作品もイベントも、共有したいことに短いアドレスを。',composerTitle:'どこへ案内しますか？',composerHint:'Webアドレスを貼り付けてください。',free:'無料',noSignup:'登録不要',qrIncluded:'QRコード付き',example:'リンクのイメージ',portfolio:'作品',event:'招待',campaign:'キャンペーン',exampleNote:'表示はサンプルです。上のフォームで作成してください。',featuresKicker:'小さなリンクに、気配りを',featuresTitle:'あなたの方法で共有。',qrTitle:'画面から、どこへでも。',qrBody:'ポスターや名刺にQRコードを。リンク先を変えても同じコードが使えます。',accessTitle:'必要な設定だけ。',accessBody:'パスワード、有効期限、アクセス数の上限を選べます。',manageFeatureTitle:'共有した後も、管理できます。',manageFeatureBody:'訪問数の確認、リンク先の変更、一時停止をマイリンクで。',stepsTitle:'貼り付けて、共有するまで。',steps:[['貼り付け','共有したいWebアドレスを入力。'],['設定','名前や必要なオプションを選択。'],['共有','リンクをコピーするかQRコードを保存。']],recoveryTitle:'キーと一緒に、リンクも移動。',recoveryBody:'端末の変更やブラウザデータの削除前に、復旧キーを保存してください。',recoveryAction:'復旧キーを見る',faqEyebrow:'困ったときは、ここから',faqTitle:'疑問に、わかりやすい答えを。',faqBody:'リンクの作成から復元までの実用ガイド。',manageEyebrow:'あなたが共有したこと',manageTitle:'あなたのリンクを、ここで管理。',manageBody:'リンクを整理し、訪問数やリンク先を管理。',deviceNote:'このブラウザが所有するリンクです。復旧キーで移動できます。',listLimit:'最新200件を表示。検索や絞り込みはこの一覧が対象です。',collection:'リンク一覧',reset:'絞り込みを解除',results:'件の一致',cancel:'キャンセル',emptyAnalytics:'この期間の訪問はありません。',footerLine:'いいことには、いいリンクを。',footerBody:'短いリンクとQRコードで、もっと共有。',footerAction:'リンクを作成'},
  ko: {...en,eyebrow:'짧은 주소로 나답게',heroFirst:'긴 이야기를,',heroSecond:'짧은 링크에.',heroBody:'작품, 행사, 나누고 싶은 소식을 짧은 주소로 공유하세요.',composerTitle:'어디로 안내할까요?',composerHint:'웹 주소를 붙여넣으면 짧게 만들어 드려요.',free:'무료',noSignup:'가입 없이',qrIncluded:'QR 코드 포함',example:'링크 미리 보기',portfolio:'작품',event:'초대',campaign:'캠페인',exampleNote:'예시입니다. 위 양식에서 실제 링크를 만드세요.',featuresKicker:'작은 링크에 담긴 배려',featuresTitle:'내 방식으로 공유하세요.',qrTitle:'화면에서 어디로든.',qrBody:'포스터와 명함에 QR 코드를 넣으세요. 목적지를 바꿔도 같은 코드를 쓸 수 있어요.',accessTitle:'필요한 만큼만 설정.',accessBody:'비밀번호, 만료일 또는 방문 횟수 제한을 선택하세요.',manageFeatureTitle:'공유한 뒤에도 관리하세요.',manageFeatureBody:'내 링크에서 방문 수를 보고, 목적지를 바꾸거나 잠시 멈추세요.',stepsTitle:'붙여넣고, 꾸미고, 공유.',steps:[['붙여넣기','공유할 웹 주소를 입력하세요.'],['설정','이름과 필요한 옵션을 선택하세요.'],['공유','링크를 복사하거나 QR 코드를 저장하세요.']],recoveryTitle:'키와 함께 링크도 이동해요.',recoveryBody:'기기 변경이나 브라우저 데이터 삭제 전에 내 링크에서 복구 키를 저장하세요.',recoveryAction:'복구 키 보기',faqEyebrow:'막혔다면 여기서 시작',faqTitle:'질문에는 명확한 답을.',faqBody:'링크 만들기부터 복구까지 실용적인 안내.',manageEyebrow:'내가 공유한 이야기',manageTitle:'내 링크를 한곳에서.',manageBody:'방문 수를 확인하고 링크와 목적지를 관리하세요.',deviceNote:'이 브라우저가 소유한 링크입니다. 복구 키로 옮길 수 있어요.',listLimit:'최근 200개 링크를 표시하며 검색과 필터는 이 목록에 적용됩니다.',collection:'내 링크 모음',reset:'필터 초기화',results:'개의 일치하는 링크',cancel:'취소',emptyAnalytics:'이 기간에는 방문이 없어요.',footerLine:'좋은 이야기에 좋은 링크를.',footerBody:'짧은 링크와 QR 코드로 더 쉽게 공유하세요.',footerAction:'링크 만들기'},
  es: {...en,eyebrow:'Menos URL. Más tú.',heroFirst:'Una gran historia.',heroSecond:'Un enlace corto.',heroBody:'Tu trabajo, tu próximo evento o algo que merece compartirse. Dale una dirección más corta.',composerTitle:'¿Adónde vamos?',composerHint:'Pega una dirección web. Nosotros la acortamos.',free:'Gratis',noSignup:'Sin registro',qrIncluded:'QR incluido',example:'Así podría verse tu enlace',portfolio:'Tu trabajo',event:'Una invitación',campaign:'Una campaña',exampleNote:'Solo un ejemplo. Crea tu enlace en el formulario de arriba.',featuresKicker:'Pequeños detalles, bien pensados',featuresTitle:'Comparte a tu manera.',qrTitle:'De la pantalla a cualquier lugar.',qrBody:'Un QR para carteles o tarjetas. Cambia el destino sin cambiar el código.',accessTitle:'Un poco más de control.',accessBody:'Añade contraseña, fecha de caducidad o límite de visitas cuando lo necesites.',manageFeatureTitle:'La historia sigue después de compartir.',manageFeatureBody:'Consulta visitas, cambia el destino o pausa enlaces en Mis enlaces.',stepsTitle:'De pegar a compartir.',steps:[['Pega','Empieza por la web que quieres compartir.'],['Personaliza','Elige un nombre y los ajustes que necesites.'],['Comparte','Copia el enlace, guarda el QR o abre el menú de compartir.']],recoveryTitle:'Tus enlaces viajan con una clave.',recoveryBody:'Guarda tu clave de recuperación antes de cambiar de dispositivo o borrar los datos del navegador.',recoveryAction:'Ver mi clave de recuperación',faqEyebrow:'Un buen lugar para resolver dudas',faqTitle:'Preguntas. Respuestas claras.',faqBody:'Desde crear un enlace hasta recuperar los anteriores.',manageEyebrow:'Tu rincón de lo que compartes',manageTitle:'Creados por ti. Gestionados aquí.',manageBody:'Ordena tus enlaces, consulta visitas y gestiona sus destinos.',deviceNote:'Enlaces de este navegador. Usa una clave de recuperación para traerlos aquí.',listLimit:'Los 200 enlaces más recientes. La búsqueda y los filtros se aplican a esta lista.',collection:'Tu colección',reset:'Borrar filtros',results:'enlaces coincidentes',cancel:'Cancelar',emptyAnalytics:'Aún no hay visitas en este periodo.',footerLine:'Las cosas buenas merecen un buen enlace.',footerBody:'Enlaces cortos, códigos QR y más espacio para compartir.',footerAction:'Crear un enlace'},
};
