import type { Locale } from '@/config/i18n';

type SystemCopy = {
  secureLink:string; passwordHint:string; showPassword:string; hidePassword:string;
  verifying:string; invalidPassword:string; linkCode:string; createNew:string; goHome:string;
  notFoundKicker:string; notFoundTitle:string; notFoundBody:string;
  errorKicker:string; unexpectedTitle:string; unexpectedBody:string; reset:string;
};

export const systemMessages:Record<Locale,SystemCopy>={
  en:{secureLink:'Secure MemoLink',passwordHint:'Your password is sent only to verify access. It is never shown on this page.',showPassword:'Show password',hidePassword:'Hide password',verifying:'Verifying…',invalidPassword:'That password did not work. Check it and try again.',linkCode:'Short link',createNew:'Create a new link',goHome:'Back to home',notFoundKicker:'404 · Lost link',notFoundTitle:'This page took a shortcut.',notFoundBody:'The address may be incorrect or the page may have moved. Let’s get you back somewhere useful.',errorKicker:'Temporary issue',unexpectedTitle:'Something interrupted the page.',unexpectedBody:'Your data is safe. Try loading this page again, or return home if the problem continues.',reset:'Reload page'},
  th:{secureLink:'MemoLink ที่ได้รับการป้องกัน',passwordHint:'รหัสผ่านจะถูกส่งไปเพื่อตรวจสอบสิทธิ์เท่านั้น และจะไม่แสดงบนหน้านี้',showPassword:'แสดงรหัสผ่าน',hidePassword:'ซ่อนรหัสผ่าน',verifying:'กำลังตรวจสอบ…',invalidPassword:'รหัสผ่านไม่ถูกต้อง กรุณาตรวจสอบแล้วลองอีกครั้ง',linkCode:'ลิงก์สั้น',createNew:'สร้างลิงก์ใหม่',goHome:'กลับหน้าแรก',notFoundKicker:'404 · หลงทางนิดหน่อย',notFoundTitle:'หน้านี้ใช้ทางลัดไปแล้ว',notFoundBody:'ที่อยู่อาจไม่ถูกต้องหรือหน้าถูกย้ายไปแล้ว กลับไปยังจุดที่ใช้งานต่อได้กันเถอะ',errorKicker:'ขัดข้องชั่วคราว',unexpectedTitle:'มีบางอย่างขัดจังหวะหน้านี้',unexpectedBody:'ข้อมูลของคุณยังปลอดภัย ลองโหลดหน้านี้อีกครั้ง หรือกลับหน้าแรกหากยังพบปัญหา',reset:'โหลดหน้าอีกครั้ง'},
  zh:{secureLink:'受保护的 MemoLink',passwordHint:'密码仅用于验证访问权限，不会显示在此页面上。',showPassword:'显示密码',hidePassword:'隐藏密码',verifying:'正在验证…',invalidPassword:'密码不正确，请检查后重试。',linkCode:'短链接',createNew:'创建新链接',goHome:'返回首页',notFoundKicker:'404 · 链接迷路了',notFoundTitle:'此页面已走了捷径。',notFoundBody:'地址可能不正确，或页面已被移动。让我们回到有用的地方。',errorKicker:'暂时出现问题',unexpectedTitle:'页面加载被中断。',unexpectedBody:'你的数据仍然安全。请重新加载页面；若问题持续，可返回首页。',reset:'重新加载'},
  ja:{secureLink:'保護された MemoLink',passwordHint:'パスワードはアクセス確認にのみ送信され、このページに表示されることはありません。',showPassword:'パスワードを表示',hidePassword:'パスワードを隠す',verifying:'確認中…',invalidPassword:'パスワードが正しくありません。確認してもう一度お試しください。',linkCode:'短縮リンク',createNew:'新しいリンクを作成',goHome:'ホームへ戻る',notFoundKicker:'404 · 迷子のリンク',notFoundTitle:'このページは近道してしまいました。',notFoundBody:'アドレスが正しくないか、ページが移動された可能性があります。利用できる場所へ戻りましょう。',errorKicker:'一時的な問題',unexpectedTitle:'ページの読み込みが中断されました。',unexpectedBody:'データは安全です。もう一度読み込むか、問題が続く場合はホームへ戻ってください。',reset:'ページを再読み込み'},
  ko:{secureLink:'보호된 MemoLink',passwordHint:'비밀번호는 접근 확인에만 전송되며 이 페이지에 표시되지 않습니다.',showPassword:'비밀번호 표시',hidePassword:'비밀번호 숨기기',verifying:'확인 중…',invalidPassword:'비밀번호가 올바르지 않습니다. 확인 후 다시 시도해 주세요.',linkCode:'단축 링크',createNew:'새 링크 만들기',goHome:'홈으로 돌아가기',notFoundKicker:'404 · 길을 잃은 링크',notFoundTitle:'이 페이지는 지름길로 떠났어요.',notFoundBody:'주소가 잘못되었거나 페이지가 이동되었을 수 있습니다. 계속할 수 있는 곳으로 돌아가세요.',errorKicker:'일시적인 문제',unexpectedTitle:'페이지 로딩이 중단되었습니다.',unexpectedBody:'데이터는 안전합니다. 페이지를 다시 불러오거나 문제가 계속되면 홈으로 돌아가세요.',reset:'페이지 다시 불러오기'},
  es:{secureLink:'MemoLink protegido',passwordHint:'La contraseña solo se envía para verificar el acceso y nunca se muestra en esta página.',showPassword:'Mostrar contraseña',hidePassword:'Ocultar contraseña',verifying:'Verificando…',invalidPassword:'La contraseña no es correcta. Compruébala e inténtalo de nuevo.',linkCode:'Enlace corto',createNew:'Crear un enlace nuevo',goHome:'Volver al inicio',notFoundKicker:'404 · Enlace perdido',notFoundTitle:'Esta página tomó un atajo.',notFoundBody:'La dirección puede ser incorrecta o la página se ha movido. Volvamos a un lugar útil.',errorKicker:'Problema temporal',unexpectedTitle:'Algo interrumpió la página.',unexpectedBody:'Tus datos están seguros. Vuelve a cargar o regresa al inicio si el problema continúa.',reset:'Volver a cargar'}

};
