import type {Locale} from './i18n';
const en={search:'Search links…',filters:'Filter & sort',all:'All',expired:'Expired',newest:'Newest',oldest:'Oldest',popular:'Most clicked',recent:'Recently visited',noResults:'No matching links',searchHint:'Try a different name or destination.',more:'More actions',share:'Share',edit:'Edit destination',save:'Save changes',qr:'QR code',moreLinks:'Show more',available:'This name is available',checking:'Checking name…',unverified:'We’ll check this name when you create the link.',helpSearch:'Search, e.g. “expired link”',contact:'Still need help?',contactAction:'Contact MemoLab',passwordToggle:'Set a password',campaignToggle:'Campaign settings',valid:'Link ready to shorten',suggest:'Try another name',recoveryHint:'Move or recover links on another device.',emptyHint:'Create your first link. You can manage it here.'};
type Copy=typeof en;
export const utilityMessages:Record<Locale,Copy>={en,
th:{search:'ค้นหาชื่อหรือปลายทาง…',filters:'กรองและเรียงลำดับ',all:'ทั้งหมด',expired:'หมดอายุ',newest:'ใหม่ล่าสุด',oldest:'เก่าสุด',popular:'คลิกมากที่สุด',recent:'เข้าชมล่าสุด',noResults:'ไม่เจอลิงก์ที่ตรงกับคำค้น',searchHint:'ลองค้นด้วยชื่อหรือปลายทางอื่น',more:'ตัวเลือกเพิ่มเติม',share:'แชร์',edit:'แก้ไขปลายทาง',save:'บันทึก',qr:'QR Code',moreLinks:'แสดงเพิ่ม',available:'ชื่อนี้ใช้ได้',checking:'กำลังตรวจสอบชื่อ…',unverified:'เราจะตรวจสอบชื่อนี้อีกครั้งเมื่อสร้างลิงก์',helpSearch:'ค้นหา เช่น “ลิงก์หมดอายุ”',contact:'ยังไม่เจอคำตอบ?',contactAction:'ติดต่อ MemoLab',passwordToggle:'ตั้งรหัสผ่าน',campaignToggle:'ตั้งค่าแคมเปญ',valid:'ลิงก์พร้อมย่อแล้ว',suggest:'ลองใช้ชื่ออื่น',recoveryHint:'ย้ายหรือกู้คืนลิงก์จากอุปกรณ์อื่น',emptyHint:'สร้างลิงก์แรก แล้วกลับมาจัดการได้ที่นี่'},
zh:{...en,search:'搜索名称或目标…',filters:'筛选与排序',all:'全部',expired:'已过期',newest:'最新',oldest:'最早',popular:'最多点击',recent:'最近访问',noResults:'没有匹配链接',searchHint:'尝试其他名称或目标地址。',more:'更多操作',share:'分享',edit:'编辑目标',save:'保存',qr:'二维码',moreLinks:'显示更多',available:'名称可用',checking:'正在检查…',unverified:'创建时将再次检查名称。',helpSearch:'搜索，例如“链接过期”',contact:'还需要帮助？',contactAction:'联系 MemoLab',passwordToggle:'设置密码',campaignToggle:'推广设置',valid:'链接可以缩短',suggest:'尝试其他名称',recoveryHint:'在其他设备上恢复链接。',emptyHint:'创建第一个链接，然后在这里管理。'},
ja:{...en,search:'名前やリンク先を検索…',filters:'絞り込みと並べ替え',all:'すべて',expired:'期限切れ',newest:'新しい順',oldest:'古い順',popular:'クリック順',recent:'最近の訪問',noResults:'一致するリンクがありません',searchHint:'別の名前やリンク先をお試しください。',more:'その他の操作',share:'共有',edit:'リンク先を編集',save:'保存',qr:'QRコード',moreLinks:'さらに表示',available:'この名前は使用できます',checking:'確認中…',unverified:'作成時に名前を再確認します。',helpSearch:'検索：例「期限切れ」',contact:'解決しませんか？',contactAction:'MemoLab に連絡',passwordToggle:'パスワードを設定',campaignToggle:'キャンペーン設定',valid:'短縮する準備ができました',suggest:'別の名前を試す',recoveryHint:'別の端末でリンクを復元します。',emptyHint:'最初のリンクを作成して、ここで管理しましょう。'},
ko:{...en,search:'이름이나 목적지 검색…',filters:'필터 및 정렬',all:'전체',expired:'만료됨',newest:'최신순',oldest:'오래된순',popular:'클릭순',recent:'최근 방문순',noResults:'일치하는 링크가 없습니다',searchHint:'다른 이름이나 목적지로 검색하세요.',more:'추가 작업',share:'공유',edit:'목적지 수정',save:'저장',qr:'QR 코드',moreLinks:'더 보기',available:'사용 가능한 이름입니다',checking:'확인 중…',unverified:'만들 때 이름을 다시 확인합니다.',helpSearch:'검색: 예 “링크 만료”',contact:'도움이 더 필요하세요?',contactAction:'MemoLab 문의',passwordToggle:'비밀번호 설정',campaignToggle:'캠페인 설정',valid:'링크를 줄일 준비가 됐어요',suggest:'다른 이름 사용',recoveryHint:'다른 기기에서 링크를 복구하세요.',emptyHint:'첫 링크를 만들고 여기서 관리하세요.'},
es:{...en,search:'Buscar nombre o destino…',filters:'Filtrar y ordenar',all:'Todos',expired:'Caducado',newest:'Más nuevos',oldest:'Más antiguos',popular:'Más clics',recent:'Visita reciente',noResults:'No hay enlaces coincidentes',searchHint:'Prueba otro nombre o destino.',more:'Más acciones',share:'Compartir',edit:'Editar destino',save:'Guardar',qr:'Código QR',moreLinks:'Mostrar más',available:'Nombre disponible',checking:'Comprobando…',unverified:'Comprobaremos el nombre al crear el enlace.',helpSearch:'Buscar, p. ej. “enlace caducado”',contact:'¿Necesitas ayuda?',contactAction:'Contactar con MemoLab',passwordToggle:'Añadir contraseña',campaignToggle:'Ajustes de campaña',valid:'Enlace listo para acortar',suggest:'Prueba otro nombre',recoveryHint:'Recupera tus enlaces en otro dispositivo.',emptyHint:'Crea tu primer enlace y gestiónalo aquí.'}};
